spring.application.name=vendas-api-back

spring.datasource.url=jdbc:postgresql://localhost:5432/venda_app
spring.datasource.username=postgres
spring.datasource.password=alca

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
