spring.application.name=vendas-api-back

spring.datasource.url=jdbc:postgresql://localhost:5432/venda_app
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

net.sf.jasperreports.extension.registry.factory.pdf=net.sf.jasperreports.pdf.PdfExtensionsRegistryFactory
